# Generated by Django 5.2.7 on 2025-12-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_client_email_alter_client_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session_sheet",
            name="user",
        ),
    ]
