# Generated by Django 5.2.7 on 2026-01-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_session_sheet_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[("residence", "Residence"), ("business", "Business")],
                        default="residence",
                        max_length=20,
                    ),
                ),
                ("street", models.CharField(max_length=20, null=True)),
                ("street_ext", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(max_length=20, null=True)),
                ("state", models.CharField(max_length=20, null=True)),
                ("zip_code", models.CharField(max_length=10, null=True)),
                ("country", models.CharField(max_length=50, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="app.profile",
                    ),
                ),
            ],
        ),
    ]
