# Generated by Django 5.2.7 on 2026-01-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="session_sheet",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Location_Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("issues", models.BooleanField(default=False)),
                ("unwanted_energies", models.BooleanField(default=False)),
                ("stuck_souls", models.BooleanField(default=False)),
                ("portals", models.BooleanField(default=False)),
                ("protection", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.location"
                    ),
                ),
            ],
        ),
    ]
