# Generated by Django 5.2.7 on 2026-01-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_session_sheet_notes_location_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location_sheet",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_sheets",
                to="app.location",
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_sheets",
                to="app.client",
            ),
        ),
    ]
