# Generated by Django 5.2.7 on 2026-01-17 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_location_sheet_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
    ]
