# Generated by Django 5.2.7 on 2026-01-17 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_client_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
    ]
