# Generated by Django 5.2.7 on 2026-01-17 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_client_first_name_alter_client_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
    ]
