# Generated by Django 5.2.7 on 2026-01-17 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_location_city_alter_location_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=models.CharField(
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain numbers only.", regex="^[0-9]+$"
                    )
                ],
            ),
        ),
    ]
