# Generated by Django 5.2.7 on 2026-01-17 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_location_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z]+$",
                    )
                ],
            ),
        ),
    ]
