# Generated by Django 5.2.7 on 2026-01-17 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_location_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
    ]
