# Generated by Django 5.2.7 on 2026-01-17 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_location_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_sheet",
            name="emotional1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="emotional2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="mental1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="mental2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="physical1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="physical2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="spiritual1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="spiritual2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
