# Generated by Django 5.2.7 on 2026-01-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_session_sheet_emotional1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_sheet",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
