# Generated by Django 5.2.7 on 2026-01-21 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_session_sheet_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="location_type",
        ),
        migrations.RemoveField(
            model_name="location",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="session_sheet",
            name="attacks",
        ),
        migrations.RemoveField(
            model_name="session_sheet",
            name="dark_entities",
        ),
        migrations.RemoveField(
            model_name="session_sheet",
            name="hinderances",
        ),
        migrations.RemoveField(
            model_name="session_sheet",
            name="social",
        ),
        migrations.RemoveField(
            model_name="session_sheet",
            name="viruses",
        ),
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("", "Select"), ("male", "Male"), ("female", "Female")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="person_or_pet",
            field=models.CharField(
                choices=[("person", "Person"), ("pet", "Pet")],
                default="person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="species",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="app.client",
            ),
        ),
        migrations.AddField(
            model_name="session_sheet",
            name="hindrances",
            field=models.CharField(
                choices=[
                    ("", "None, or select here."),
                    ("dark_entities", "Dark Entities"),
                    ("attacks", "Attacks"),
                    ("societal", "Societal"),
                    ("viruses", "Viruses"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session_sheet",
            name="how_many",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain numbers only.", regex="^[0-9]+$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="session_sheet",
            name="to_whom",
            field=models.CharField(
                blank=True,
                max_length=999,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain numbers only.", regex="^[0-9]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="chakras",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed_to_open", "Closed > Open"),
                    ("see_notes", "See Notes"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="emotional1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="emotional2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="mental1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="mental2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="physical1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="physical2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="spiritual1",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="spiritual2",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(999999)]
            ),
        ),
    ]
