# Generated by Django 5.2.7 on 2026-01-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_location_location_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations_by_profile",
                to="app.profile",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations_by_client",
                to="app.client",
            ),
        ),
    ]
