# Generated by Django 5.2.7 on 2026-02-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_location_profile_alter_location_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
