# Generated by Django 5.2.7 on 2026-02-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_client_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "Select"), ("male", "Male"), ("female", "Female")],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
