# Generated by Django 5.2.7 on 2026-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_client_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_sheet",
            name="hindrances",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None, or select here."),
                    ("dark_entities", "Dark Entities"),
                    ("attacks", "Attacks"),
                    ("societal", "Societal"),
                    ("viruses", "Viruses"),
                ],
                default="",
                max_length=200,
            ),
        ),
    ]
