# Generated by Django 5.2.7 on 2026-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_session_sheet_hindrances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location_sheet",
            name="portals",
        ),
        migrations.RemoveField(
            model_name="location_sheet",
            name="stuck_souls",
        ),
        migrations.RemoveField(
            model_name="location_sheet",
            name="unwanted_energies",
        ),
        migrations.AlterField(
            model_name="location_sheet",
            name="issues",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unwanted_energies", "Unwanted Energies"),
                    ("stuck_souls", "Stuck Souls"),
                    ("portals", "Portals"),
                ],
                default="",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="hindrances",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dark_entities", "Dark Entities"),
                    ("attacks", "Attacks"),
                    ("societal", "Societal"),
                    ("viruses", "Viruses"),
                ],
                default="",
                max_length=200,
            ),
        ),
    ]
