# Generated by Django 5.2.7 on 2026-02-22 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_location_sheet_portals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session_sheet",
            name="hindrances",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="session_sheet",
            name="to_whom",
            field=models.CharField(
                blank=True,
                max_length=999,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This field may contain letters only.",
                        regex="^[a-zA-Z ]+$",
                    )
                ],
            ),
        ),
    ]
